/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
usage: rasa [-h] [--version]
            {init,run,shell,train,interactive,telemetry,test,visualize,data,export,x,evaluate} ...
rasa: error: argument {init,run,shell,train,interactive,telemetry,test,visualize,data,export,x,evaluate}: invalid choice: 'action' (choose from 'init', 'run', 'shell', 'train', 'interactive', 'telemetry', 'test', 'visualize', 'data', 'export', 'x', 'evaluate')
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 03:00:25 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 03:00:27 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 03:00:27 INFO     rasa.core.processor  - Loading model models/20241012-024901-annoying-canteen.tar.gz...
2024-10-12 03:01:05 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2024-10-12 03:01:21 INFO     root  - Rasa server is up and running.
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 03:03:02 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 03:03:04 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 03:03:04 INFO     rasa.core.processor  - Loading model models/20241012-024901-annoying-canteen.tar.gz...
[2024-10-12 03:03:15 +0000] [6842] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1204, in run
    serve_single(server_settings)
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 61, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 2000, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 191, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1524, in _listener
    await maybe_coro
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/run.py", line 290, in load_agent_on_start
    app.ctx.agent = await agent.load_agent(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/agent.py", line 254, in load_agent
    agent.load_model(model_path)
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/agent.py", line 352, in load_model
    self.processor = MessageProcessor(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 105, in __init__
    self.model_filename, self.model_metadata, self.graph_runner = self._load_model(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 142, in _load_model
    metadata, runner = loader.load_predict_graph_runner(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/loader.py", line 29, in load_predict_graph_runner
    runner = graph_runner_class.create(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 51, in create
    return cls(graph_schema, model_storage, execution_context, hooks)
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 37, in __init__
    self._instantiated_nodes: Dict[Text, GraphNode] = self._instantiate_nodes(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 60, in _instantiate_nodes
    return {
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 61, in <dictcomp>
    node_name: GraphNode.from_schema_node(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 566, in from_schema_node
    return cls(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 392, in __init__
    self._load_component()
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 403, in _load_component
    self._component: GraphComponent = constructor(  # type: ignore[no-redef]
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1125, in load
    return cls._load(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1156, in _load
    model = cls._load_model(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1249, in _load_model
    model = cls._load_model_class(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1280, in _load_model_class
    return cls.model_class().load(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/tensorflow/models.py", line 445, in load
    model.fit(data_generator, verbose=False)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 1685, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 894, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 959, in _call
    return self._no_variable_creation_fn(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 142, in __call__
    filtered_flat_args) = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 396, in _maybe_define_function
    concrete_function = self._create_concrete_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 300, in _create_concrete_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py", line 1214, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 667, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py", line 1189, in autograph_handler
    return autograph.converted_call(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileqm3iezkf.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 1268, in step_function
    outputs = model.distribute_strategy.run(run_step, args=(data,))
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1316, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2895, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 3696, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 1249, in run_step
    outputs = model.train_step(data)
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/tensorflow/models.py", line 161, in train_step
    prediction_loss = self.batch_loss(batch_in)
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1649, in batch_loss
    loss = self._batch_loss_intent(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1682, in _batch_loss_intent
    label = self._create_bow(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1514, in _create_bow
    x, _ = self._tf_layers[f"feature_combining_layer.{name}"](
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer.py", line 1145, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_file0n2fiin0.py", line 35, in tf__call
    sequence_features_combined = ag__.converted_call(ag__.ld(self)._combine_sequence_level_features, (ag__.ld(sequence_features), ag__.ld(mask_sequence), ag__.ld(training)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_file9p633whi.py", line 38, in tf___combine_sequence_level_features
    ag__.if_stmt(ag__.ld(self)._feature_types_present[ag__.ld(SEQUENCE)], if_body, else_body, get_state, set_state, ('do_return', 'retval_'), 2)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1266, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1319, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_file9p633whi.py", line 21, in if_body
    sequence_features_combined = ag__.converted_call(ag__.ld(self)._tf_layers[f'sparse_dense.{ag__.ld(SEQUENCE)}'], ((ag__.ld(sequence_features),),), dict(training=ag__.ld(training)), fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer.py", line 1145, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filezhvfur8k.py", line 50, in tf__call
    ag__.for_stmt(ag__.ld(features), None, loop_body, get_state_1, set_state_1, (), {'iterate_names': 'f'})
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 451, in for_stmt
    for_fn(iter_, extra_test, body, get_state, set_state, symbol_names, opts)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 502, in _py_for_stmt
    body(target)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 468, in protected_body
    original_body(protected_iter)
  File "/tmp/__autograph_generated_filezhvfur8k.py", line 47, in loop_body
    ag__.if_stmt(ag__.converted_call(ag__.ld(isinstance), (ag__.ld(f), ag__.ld(tf).SparseTensor), None, fscope), if_body, else_body, get_state, set_state, ('f',), 1)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1266, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1319, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_filezhvfur8k.py", line 42, in if_body
    f = ag__.converted_call(ag__.ld(self)._process_sparse_feature, (ag__.ld(f), ag__.ld(training)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_filefojy58sc.py", line 27, in tf___process_sparse_feature
    feature = ag__.converted_call(ag__.ld(self)._tf_layers[ag__.ld(self).SPARSE_TO_DENSE], (ag__.ld(feature),), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer.py", line 1145, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileh0e57zzj.py", line 50, in tf__call
    ag__.if_stmt(ag__.converted_call(ag__.ld(len), (ag__.ld(inputs).shape,), None, fscope) == 3, if_body_1, else_body_1, get_state_1, set_state_1, ('outputs',), 1)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1266, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1319, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_fileh0e57zzj.py", line 45, in if_body_1
    outputs = ag__.converted_call(ag__.ld(tf).reshape, (ag__.ld(outputs), (ag__.converted_call(ag__.ld(tf).shape, (ag__.ld(inputs),), None, fscope)[0], ag__.converted_call(ag__.ld(tf).shape, (ag__.ld(inputs),), None, fscope)[1], ag__.ld(self).units)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/array_ops.py", line 1114, in _slice_helper
    return strided_slice(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/array_ops.py", line 1287, in strided_slice
    op = gen_array_ops.strided_slice(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 10729, in strided_slice
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py", line 707, in _create_op_internal
    return super()._create_op_internal(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 3814, in _create_op_internal
    ret = Operation(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 2112, in __init__
    c_op = _create_c_op(g, node_def, inputs, control_input_ops, op_def=op_def)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 1970, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/rasa/__main__.py", line 133, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.10/dist-packages/rasa/cli/run.py", line 93, in run
    rasa.run(**vars(args))
  File "/usr/local/lib/python3.10/dist-packages/rasa/api.py", line 56, in run
    rasa.core.run.serve_application(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/run.py", line 268, in serve_application
    app.run(
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1204, in run
    serve_single(server_settings)
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 130, in serve
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 61, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 2000, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 191, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1524, in _listener
    await maybe_coro
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/run.py", line 290, in load_agent_on_start
    app.ctx.agent = await agent.load_agent(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/agent.py", line 254, in load_agent
    agent.load_model(model_path)
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/agent.py", line 352, in load_model
    self.processor = MessageProcessor(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 105, in __init__
    self.model_filename, self.model_metadata, self.graph_runner = self._load_model(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 142, in _load_model
    metadata, runner = loader.load_predict_graph_runner(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/loader.py", line 29, in load_predict_graph_runner
    runner = graph_runner_class.create(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 51, in create
    return cls(graph_schema, model_storage, execution_context, hooks)
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 37, in __init__
    self._instantiated_nodes: Dict[Text, GraphNode] = self._instantiate_nodes(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 60, in _instantiate_nodes
    return {
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 61, in <dictcomp>
    node_name: GraphNode.from_schema_node(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 566, in from_schema_node
    return cls(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 392, in __init__
    self._load_component()
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 403, in _load_component
    self._component: GraphComponent = constructor(  # type: ignore[no-redef]
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1125, in load
    return cls._load(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1156, in _load
    model = cls._load_model(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1249, in _load_model
    model = cls._load_model_class(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1280, in _load_model_class
    return cls.model_class().load(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/tensorflow/models.py", line 445, in load
    model.fit(data_generator, verbose=False)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 1685, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 894, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 959, in _call
    return self._no_variable_creation_fn(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 142, in __call__
    filtered_flat_args) = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 396, in _maybe_define_function
    concrete_function = self._create_concrete_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 300, in _create_concrete_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py", line 1214, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 667, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py", line 1189, in autograph_handler
    return autograph.converted_call(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileqm3iezkf.py", line 15, in tf__train_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 1268, in step_function
    outputs = model.distribute_strategy.run(run_step, args=(data,))
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1316, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2895, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 3696, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 1249, in run_step
    outputs = model.train_step(data)
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/tensorflow/models.py", line 161, in train_step
    prediction_loss = self.batch_loss(batch_in)
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1649, in batch_loss
    loss = self._batch_loss_intent(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1682, in _batch_loss_intent
    label = self._create_bow(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1514, in _create_bow
    x, _ = self._tf_layers[f"feature_combining_layer.{name}"](
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer.py", line 1145, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_file0n2fiin0.py", line 35, in tf__call
    sequence_features_combined = ag__.converted_call(ag__.ld(self)._combine_sequence_level_features, (ag__.ld(sequence_features), ag__.ld(mask_sequence), ag__.ld(training)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_file9p633whi.py", line 38, in tf___combine_sequence_level_features
    ag__.if_stmt(ag__.ld(self)._feature_types_present[ag__.ld(SEQUENCE)], if_body, else_body, get_state, set_state, ('do_return', 'retval_'), 2)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1266, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1319, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_file9p633whi.py", line 21, in if_body
    sequence_features_combined = ag__.converted_call(ag__.ld(self)._tf_layers[f'sparse_dense.{ag__.ld(SEQUENCE)}'], ((ag__.ld(sequence_features),),), dict(training=ag__.ld(training)), fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer.py", line 1145, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filezhvfur8k.py", line 50, in tf__call
    ag__.for_stmt(ag__.ld(features), None, loop_body, get_state_1, set_state_1, (), {'iterate_names': 'f'})
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 451, in for_stmt
    for_fn(iter_, extra_test, body, get_state, set_state, symbol_names, opts)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 502, in _py_for_stmt
    body(target)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 468, in protected_body
    original_body(protected_iter)
  File "/tmp/__autograph_generated_filezhvfur8k.py", line 47, in loop_body
    ag__.if_stmt(ag__.converted_call(ag__.ld(isinstance), (ag__.ld(f), ag__.ld(tf).SparseTensor), None, fscope), if_body, else_body, get_state, set_state, ('f',), 1)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1266, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1319, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_filezhvfur8k.py", line 42, in if_body
    f = ag__.converted_call(ag__.ld(self)._process_sparse_feature, (ag__.ld(f), ag__.ld(training)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_filefojy58sc.py", line 27, in tf___process_sparse_feature
    feature = ag__.converted_call(ag__.ld(self)._tf_layers[ag__.ld(self).SPARSE_TO_DENSE], (ag__.ld(feature),), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 331, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/engine/base_layer.py", line 1145, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 96, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileh0e57zzj.py", line 50, in tf__call
    ag__.if_stmt(ag__.converted_call(ag__.ld(len), (ag__.ld(inputs).shape,), None, fscope) == 3, if_body_1, else_body_1, get_state_1, set_state_1, ('outputs',), 1)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1266, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1319, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_fileh0e57zzj.py", line 45, in if_body_1
    outputs = ag__.converted_call(ag__.ld(tf).reshape, (ag__.ld(outputs), (ag__.converted_call(ag__.ld(tf).shape, (ag__.ld(inputs),), None, fscope)[0], ag__.converted_call(ag__.ld(tf).shape, (ag__.ld(inputs),), None, fscope)[1], ag__.ld(self).units)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/array_ops.py", line 1114, in _slice_helper
    return strided_slice(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 1176, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/array_ops.py", line 1287, in strided_slice
    op = gen_array_ops.strided_slice(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 10729, in strided_slice
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py", line 707, in _create_op_internal
    return super()._create_op_internal(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 3814, in _create_op_internal
    ret = Operation(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 2112, in __init__
    c_op = _create_c_op(g, node_def, inputs, control_input_ops, op_def=op_def)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 1970, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
KeyboardInterrupt
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 03:03:27 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 03:03:28 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 03:03:28 INFO     rasa.core.processor  - Loading model models/20241012-024901-annoying-canteen.tar.gz...
2024-10-12 03:04:03 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2024-10-12 03:04:19 INFO     root  - Rasa server is up and running.
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2024-10-12 03:41:59 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2024-10-12 03:41:59 INFO     rasa_sdk.endpoint  - Starting plugins...
2024-10-12 03:41:59 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 03:42:03 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 03:42:05 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 03:42:05 INFO     rasa.core.processor  - Loading model models/20241012-024901-annoying-canteen.tar.gz...
2024-10-12 03:42:42 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2024-10-12 03:42:58 INFO     root  - Rasa server is up and running.
[2024-10-12 03:42:58 +0000] [16307] [ERROR] Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
2024-10-12 12:40:57 DEBUG    rasa.telemetry  - Could not read telemetry settings from configuration file: Configuration 'metrics' key not found.
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2024-10-12 12:40:57 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2024-10-12 12:40:57 INFO     rasa_sdk.endpoint  - Starting plugins...
2024-10-12 12:40:57 DEBUG    rasa_sdk.plugin  - No plugins found: No module named 'rasa_sdk_plugins'
2024-10-12 12:40:57 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2024-10-12 12:40:57 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 12:41:03 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 12:41:06 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 12:41:07 INFO     rasa.core.processor  - Loading model models/20241012-024901-annoying-canteen.tar.gz...
2024-10-12 12:41:44 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2024-10-12 12:42:01 INFO     root  - Rasa server is up and running.
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2024-10-12 13:34:18 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2024-10-12 13:34:18 INFO     rasa_sdk.executor  - Registered function for 'action_check_answer'.
2024-10-12 13:34:18 INFO     rasa_sdk.endpoint  - Starting plugins...
2024-10-12 13:34:18 DEBUG    rasa_sdk.plugin  - No plugins found: No module named 'rasa_sdk_plugins'
2024-10-12 13:34:18 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2024-10-12 13:34:18 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5055): address already in use
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 13:34:23 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 13:34:25 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 13:34:25 INFO     rasa.core.processor  - Loading model models/20241012-024901-annoying-canteen.tar.gz...
2024-10-12 13:35:01 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2024-10-12 13:35:18 INFO     root  - Rasa server is up and running.
[2024-10-12 13:35:18 +0000] [16465] [ERROR] Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2024-10-12 13:51:16 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2024-10-12 13:51:16 INFO     rasa_sdk.executor  - Registered function for 'action_check_answer'.
2024-10-12 13:51:16 INFO     rasa_sdk.endpoint  - Starting plugins...
2024-10-12 13:51:16 DEBUG    rasa_sdk.plugin  - No plugins found: No module named 'rasa_sdk_plugins'
2024-10-12 13:51:16 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2024-10-12 13:51:16 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5055): address already in use
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 13:51:21 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 13:51:22 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 13:51:23 INFO     rasa.core.processor  - Loading model models/20241012-024901-annoying-canteen.tar.gz...
2024-10-12 13:51:58 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2024-10-12 13:52:16 INFO     root  - Rasa server is up and running.
[2024-10-12 13:52:16 +0000] [20580] [ERROR] Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2024-10-12 14:26:39 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
2024-10-12 14:26:39 INFO     rasa_sdk.executor  - Registered function for 'action_default_fallback'.
2024-10-12 14:26:39 INFO     rasa_sdk.endpoint  - Starting plugins...
2024-10-12 14:26:39 DEBUG    rasa_sdk.plugin  - No plugins found: No module named 'rasa_sdk_plugins'
2024-10-12 14:26:39 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2024-10-12 14:26:39 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5055): address already in use
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 14:26:43 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 14:26:44 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 14:26:45 INFO     rasa.core.processor  - Loading model models/20241012-142607-fixed-taper.tar.gz...
2024-10-12 14:27:03 INFO     root  - Rasa server is up and running.
[2024-10-12 14:27:03 +0000] [29611] [ERROR] Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
(0lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk(B
(0x(B Rasa Open Source reports anonymous usage telemetry to help improve the product (0x(B
(0x(B for all its users.                                                             (0x(B
(0x(B                                                                                (0x(B
(0x(B If you'd like to opt-out, you can use `rasa telemetry disable`.                (0x(B
(0x(B To learn more, check out https://rasa.com/docs/rasa/telemetry/telemetry.       (0x(B
(0mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj(B
(0lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk(B
(0x(B Rasa Open Source reports anonymous usage telemetry to help improve the product (0x(B
(0x(B for all its users.                                                             (0x(B
(0x(B                                                                                (0x(B
(0x(B If you'd like to opt-out, you can use `rasa telemetry disable`.                (0x(B
(0x(B To learn more, check out https://rasa.com/docs/rasa/telemetry/telemetry.       (0x(B
(0mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj(B
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 14:29:56 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 14:29:58 INFO     root  - Starting Rasa server on http://0.0.0.0:5006
2024-10-12 14:29:58 INFO     rasa.core.processor  - Loading model models/20241012-142607-fixed-taper.tar.gz...
2024-10-12 14:30:00 ERROR    rasa.core.agent  - Could not load model due to Error initializing graph component for node run_DIETClassifier5..
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 403, in _load_component
    self._component: GraphComponent = constructor(  # type: ignore[no-redef]
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1125, in load
    return cls._load(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1156, in _load
    model = cls._load_model(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1249, in _load_model
    model = cls._load_model_class(
  File "/usr/local/lib/python3.10/dist-packages/rasa/nlu/classifiers/diet_classifier.py", line 1280, in _load_model_class
    return cls.model_class().load(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/tensorflow/models.py", line 445, in load
    model.fit(data_generator, verbose=False)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/tf_stack.py", line 61, in __exit__
    assert top is self, 'Concurrent access?'
AssertionError: Concurrent access?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/agent.py", line 254, in load_agent
    agent.load_model(model_path)
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/agent.py", line 352, in load_model
    self.processor = MessageProcessor(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 105, in __init__
    self.model_filename, self.model_metadata, self.graph_runner = self._load_model(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 142, in _load_model
    metadata, runner = loader.load_predict_graph_runner(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/loader.py", line 29, in load_predict_graph_runner
    runner = graph_runner_class.create(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 51, in create
    return cls(graph_schema, model_storage, execution_context, hooks)
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 37, in __init__
    self._instantiated_nodes: Dict[Text, GraphNode] = self._instantiate_nodes(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 60, in _instantiate_nodes
    return {
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/runner/dask.py", line 61, in <dictcomp>
    node_name: GraphNode.from_schema_node(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 566, in from_schema_node
    return cls(
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 392, in __init__
    self._load_component()
  File "/usr/local/lib/python3.10/dist-packages/rasa/engine/graph.py", line 416, in _load_component
    raise GraphComponentException(
rasa.engine.exceptions.GraphComponentException: Error initializing graph component for node run_DIETClassifier5.
2024-10-12 14:30:00 INFO     root  - Rasa server is up and running.
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 14:30:28 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 14:30:29 INFO     root  - Starting Rasa server on http://0.0.0.0:5006
2024-10-12 14:30:29 INFO     rasa.core.processor  - Loading model models/20241012-142607-fixed-taper.tar.gz...
2024-10-12 14:30:46 INFO     root  - Rasa server is up and running.
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2024-10-12 14:32:30 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2024-10-12 14:32:30 INFO     rasa_sdk.executor  - Registered function for 'action_default_fallback'.
2024-10-12 14:32:30 INFO     rasa_sdk.endpoint  - Starting plugins...
2024-10-12 14:32:30 DEBUG    rasa_sdk.plugin  - No plugins found: No module named 'rasa_sdk_plugins'
2024-10-12 14:32:30 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2024-10-12 14:32:30 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 14:32:33 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 14:32:35 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 14:32:35 INFO     rasa.core.processor  - Loading model models/20241012-142607-fixed-taper.tar.gz...
2024-10-12 14:32:53 INFO     root  - Rasa server is up and running.
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3540514,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.3540514,"use_text_for_featurization":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_listen"},"latest_action_name":"action_listen"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3627763,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3681207,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3730924,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3730924,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3778887,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3730924,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3778887,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3827252,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3730924,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3778887,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3827252,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3876662,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3730924,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3778887,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3827252,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3876662,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3925495,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3730924,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3778887,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3827252,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3876662,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3925495,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.3972394,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3730924,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3778887,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3827252,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3876662,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3925495,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3972394,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:32:59 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/endpoint.py", line 113, in webhook
    result = await executor.run(action_call)
  File "/usr/local/lib/python3.10/dist-packages/rasa_sdk/executor.py", line 399, in run
    action(dispatcher, tracker, domain)
  File "/content/my-chatbot-project/actions/actions.py", line 11, in run
    response = self.call_huggingface_api(user_message)
  File "/content/my-chatbot-project/actions/actions.py", line 25, in call_huggingface_api
    response = requests.post(url, headers=headers, json=data)
NameError: name 'requests' is not defined
2024-10-12 14:32:59 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 780, in run
    response: Any = await self.action_endpoint.request(
  File "/usr/local/lib/python3.10/dist-packages/rasa/utils/endpoints.py", line 184, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"name \'requests\' is not defined","request_body":{"next_action":"action_default_fallback","sender_id":"user1","tracker":{"sender_id":"user1","slots":{"session_started_metadata":null},"latest_message":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"latest_event_time":1728743579.402747,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1728743579.3363283,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1728743579.3364413,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"}},{"event":"action","timestamp":1728743579.336466,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1728743579.3525114,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"text":"apakah sudah terkoneksi?","parse_data":{"intent":{"name":"ask_knowledge","confidence":0.9987591505050659},"entities":[],"text":"apakah sudah terkoneksi?","message_id":"2284fa94dd43436bacbff79814f9b000","metadata":{},"text_tokens":[[0,6],[7,12],[13,23]],"intent_ranking":[{"name":"ask_knowledge","confidence":0.9987591505050659},{"name":"greet","confidence":0.0009240716462954879},{"name":"bot_challenge","confidence":0.0001268024352611974},{"name":"goodbye","confidence":8.231063839048147e-5},{"name":"mood_unhappy","confidence":4.5596145355375484e-5},{"name":"deny","confidence":3.23829626722727e-5},{"name":"affirm","confidence":1.8428727344144136e-5},{"name":"mood_great","confidence":1.124057325796457e-5}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rest","message_id":"2284fa94dd43436bacbff79814f9b000"},{"event":"user_featurization","timestamp":1728743579.36274,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"use_text_for_featurization":false},{"event":"action","timestamp":1728743579.3627763,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3681207,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3730924,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3778887,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3827252,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3876662,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3925495,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.3972394,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false},{"event":"action","timestamp":1728743579.402747,"metadata":{"model_id":"4983b451951a49c485729192f551c7d4","assistant_id":"20241012-141205-tan-export"},"name":"action_default_fallback","policy":"RulePolicy","confidence":0.3,"action_text":null,"hide_rule_turn":false}],"latest_input_channel":"rest","active_loop":{},"latest_action":{"action_name":"action_default_fallback"},"latest_action_name":"action_default_fallback"},"version":"3.6.20","domain":{"version":"3.1","intents":["action_check_answer","action_default_fallback","affirm","ask_knowledge","bot_challenge","deny","goodbye","greet","mood_great","mood_unhappy","nlu_fallback"],"actions":["action_check_answer","action_default_fallback"],"responses":{"utter_default_fallback":[{"text":"Maaf, saya tidak mengerti pertanyaan Anda. Saya akan mencoba menjawab dengan bantuan AI..."}],"utter_greet":[{"text":"Hey! How are you?"}],"utter_knowledge":[{"text":"Tunggu sebentar, saya sedang memproses jawaban dari AI..."}],"utter_cheer_up":[{"text":"Here is something to cheer you up:","image":"https:\\/\\/i.imgur.com\\/nGF1K8f.jpg"}],"utter_did_that_help":[{"text":"Did that help you?"}],"utter_happy":[{"text":"Great, carry on!"}],"utter_goodbye":[{"text":"Bye"}],"utter_iamabot":[{"text":"I am a bot, powered by Rasa."}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}}}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/processor.py", line 982, in _run_action
    events = await action.run(
  File "/usr/local/lib/python3.10/dist-packages/rasa/core/actions/action.py", line 810, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_default_fallback'
2024-10-12 14:32:59 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'user1'.
2024-10-12 14:33:14 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'user1'.
2024-10-12 14:34:36 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'user1'.
2024-10-12 14:35:50 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'user1'.
2024-10-12 14:37:58 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'user1'.
2024-10-12 14:44:09 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'user1'.
2024-10-12 14:55:45 WARNING  rasa.core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'user1'.
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 14:57:09 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 14:57:11 INFO     root  - Starting Rasa server on http://0.0.0.0:5006
2024-10-12 14:57:12 INFO     rasa.core.processor  - Loading model models/20241012-145606-warm-counterpoint.tar.gz...
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.cloud')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3121: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2024-10-12 14:57:19 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2024-10-12 14:57:19 INFO     rasa_sdk.executor  - Registered function for 'action_default_fallback'.
2024-10-12 14:57:19 INFO     rasa_sdk.endpoint  - Starting plugins...
2024-10-12 14:57:19 DEBUG    rasa_sdk.plugin  - No plugins found: No module named 'rasa_sdk_plugins'
2024-10-12 14:57:19 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2024-10-12 14:57:19 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
/usr/local/lib/python3.10/dist-packages/sanic_cors/extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
2024-10-12 14:57:25 INFO     numexpr.utils  - NumExpr defaulting to 2 threads.
2024-10-12 14:57:27 INFO     root  - Starting Rasa server on http://0.0.0.0:5005
2024-10-12 14:57:28 INFO     rasa.core.processor  - Loading model models/20241012-145606-warm-counterpoint.tar.gz...
2024-10-12 14:57:43 INFO     root  - Rasa server is up and running.
Unable to start server
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1790, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5006): address already in use
2024-10-12 14:57:54 INFO     root  - Rasa server is up and running.
2024-10-12 14:57:57 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:57:57 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 14:57:59 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 None
2024-10-12 14:57:59 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 14:58:13 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:58:13 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 14:58:16 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 None
2024-10-12 14:58:16 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 14:58:26 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 14:58:26 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 14:58:37 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 None
2024-10-12 14:58:37 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:02:36 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:02:36 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:02:36 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 31
2024-10-12 15:02:36 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:02:46 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:02:46 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:02:50 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 None
2024-10-12 15:02:50 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:03:00 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:03:00 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:03:01 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 503 96
2024-10-12 15:03:01 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:03:55 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:03:55 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:03:58 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 None
2024-10-12 15:03:58 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:04:13 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:04:13 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:04:14 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 471
2024-10-12 15:04:14 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:04:57 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:04:57 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:04:58 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 471
2024-10-12 15:04:58 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:05:05 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:05:05 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:05:06 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 200 439
2024-10-12 15:05:06 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
2024-10-12 15:05:14 DEBUG    rasa_sdk.executor  - Received request to run 'action_default_fallback'
2024-10-12 15:05:14 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api-inference.huggingface.co:443
2024-10-12 15:05:14 DEBUG    urllib3.connectionpool  - https://api-inference.huggingface.co:443 "POST /models/openai-community/gpt2 HTTP/11" 422 None
2024-10-12 15:05:14 DEBUG    rasa_sdk.executor  - Finished running 'action_default_fallback'
